name: Test two actions
on:
  push:
    paths:
      - .github/workflows/call-two-actions-from-another-repo.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: managedkaos/github-actions-two-actions/action1@master
      - uses: managedkaos/github-actions-two-actions/action2@master
      - uses: lisadean/the-sorting-hat@v1.3.0
