name: set-env

on:
  push:
    paths:
      - .github/workflows/set-env.yml

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - run: echo nju33 | xargs -I{} echo "::set-env name=NAME::{}"
      - run: echo "$NAME"
